/* Copyright (c) 2017, EPL-Vizards
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of the EPL-Vizards nor the
 *       names of its contributors may be used to endorse or promote products
 *       derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL EPL-Vizards BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
/*!
 * \file EPLVizDefines.hpp
 * \note This file is automatically generated.
 * Please edit only defines.in.hpp in the project root
 */

#pragma once

#define EPL_VIZ_ENABLE_MOCKING @CM_ENABLE_MOCKING@

#ifndef mockable
#if EPL_VIZ_ENABLE_MOCKING
#define mockable virtual
#else
#define mockable
#endif
#endif

namespace EPL_Viz {

namespace constants {

const int   EPL_VIZ_VERSION_MAJOR     = @CM_VERSION_MAJOR@;
const int   EPL_VIZ_VERSION_MINOR     = @CM_VERSION_MINOR@;
const int   EPL_VIZ_VERSION_SUBMINOR  = @CM_VERSION_SUBMINOR@;
const int   EPL_VIZ_GIT_LAST_TAG_DIFF = @CM_TAG_DIFF@;
const char * const EPL_VIZ_VERSION_GIT       = "@CM_VERSION_GIT@";
const char * const EPL_VIZ_INSTALL_PREFIX    = "@CMAKE_INSTALL_PREFIX@";
}
}
